FROM alpine:3.7
RUN echo -e 'https://mirrors.aliyun.com/alpine/v3.7/main/\nhttps://mirrors.aliyun.com/alpine/v3.7/community/' > /etc/apk/repositories && \
    apk update && apk add build-base tzdata nodejs cairo-dev jpeg-dev pango-dev freetype-dev giflib-dev&& \
    cp -r -f /usr/share/zoneinfo/Asia/Chongqing /etc/localtime && \
    cd / && npm i -d canvas@1.6.9 echarts@3.8.5 underscore@1.8.3 --registry=https://registry.npm.taobao.org
